apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: workloads-local
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - postgresql-database/local
