apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      version: '1.26.0'
      sourceRef:
        kind: HelmRepository
        name: cnpg-charts
        namespace: flux-system
  targetNamespace: cnpg-system
  install:
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    monitoring:
      podMonitorEnabled: false
