apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: database
spec:
  instances: 1
  
  # Local environment resource settings
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 4Gi

  # Increased storage for local development
  storage:
    size: 30Gi
    
  # For local dev, set fewer worker processes
  postgresql:
    parameters:
      max_parallel_workers: "4"
      max_worker_processes: "4"
      autovacuum_max_workers: "1"
  
  # Enable monitoring with custom metrics
  monitoring:
    enablePodMonitor: true
    customQueriesConfigMap:
    - name: postgres-custom-metrics
      key: custom-queries.yaml