apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-custom-metrics
  namespace: database
data:
  custom-queries.yaml: |
    pg_database:
      query: |
        SELECT
          d.datname as database_name,
          pg_database_size(d.datname) as size_bytes
        FROM pg_database d
      metrics:
        - database_name:
            usage: "LABEL"
            description: "Database name"
        - size_bytes:
            usage: "GAUGE"
            description: "Database size in bytes"
    pg_stat_user_tables:
      query: |
        SELECT
          schemaname,
          relname as table_name,
          n_tup_ins as inserts,
          n_tup_upd as updates,
          n_tup_del as deletes,
          n_live_tup as live_tuples,
          n_dead_tup as dead_tuples
        FROM pg_stat_user_tables
      metrics:
        - schemaname:
            usage: "LABEL"
            description: "Schema name"
        - table_name:
            usage: "LABEL"
            description: "Table name"
        - inserts:
            usage: "COUNTER"
            description: "Number of inserts"
        - updates:
            usage: "COUNTER"
            description: "Number of updates"
        - deletes:
            usage: "COUNTER"
            description: "Number of deletes"
        - live_tuples:
            usage: "GAUGE"
            description: "Number of live tuples"
        - dead_tuples:
            usage: "GAUGE"
            description: "Number of dead tuples"
