apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-local
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - cloudnative-pg/local
