# on actual server we need to encrypt this using sops or others mechanism
apiVersion: v1
kind: Secret
metadata:
    name: postgres-migration-secrets
    namespace: database
stringData:
    db_name: pg-core
    db_host: pg-core-rw.database.svc.cluster.local
    db_password: pguserpassword
    db_port: "5432"
    db_user: pguser
