apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: database
spec:
  instances: 3
  
  # Local environment resource settings
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 1Gi

  # Increased storage for local development
  storage:
    size: 10Gi
    
  # For local dev, set fewer worker processes
  postgresql:
    parameters:
      max_parallel_workers: "4"
      max_worker_processes: "4"
      autovacuum_max_workers: "1"
  
  # Enable monitoring with custom metrics
  monitoring:
    enablePodMonitor: true
    customQueriesConfigMap:
    - name: postgres-custom-metrics
      key: custom-queries.yaml
  
  spec:
  affinity:
    podAntiAffinity: {}
