apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - postgres-superuser-secret.yaml
  - postgres-user-secret.yaml
  - servicemonitor.yaml
  - custom-metrics.yaml

patches:
  - path: cluster-patch.yaml
    target:
      kind: Cluster
      name: postgres-cluster
