---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: database
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5-standard-bookworm
  instances: 1
  startDelay: 30
  stopDelay: 120
  smartShutdownTimeout: 120
  failoverDelay: 0
  switchoverDelay: 600
  primaryUpdateStrategy: unsupervised
  
  superuserSecret:
    name: postgres-super-secret
  enableSuperuserAccess: true
  
  bootstrap:
    initdb:
      database: app_db
      owner: app_user
      secret:
        name: postgres-user-secret
      postInitTemplateSQL:
        - alter user app_user createdb;
        - SELECT pg_reload_conf();
        - CREATE DATABASE app;
        - ALTER DATABASE app OWNER TO app_user;
        - GRANT ALL PRIVILEGES ON DATABASE app TO app_user;
        - GRANT USAGE, CREATE ON SCHEMA public TO app_user;
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app_user;
        - GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO app_user;
        - ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO app_user;
        - ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO app_user;
  
  postgresql:
    shared_preload_libraries:
      - auto_explain
      - pg_stat_statements
      - pgaudit
    parameters:
      timezone: "Asia/Jakarta"
      max_connections: "256"
      shared_buffers: "128MB"
      work_mem: "4MB"
      effective_cache_size: "512MB"
      maintenance_work_mem: "64MB"
      max_parallel_workers: "12"
      max_worker_processes: "12"
      
      # Vacuum settings
      autovacuum_vacuum_threshold: "20000"
      autovacuum_analyze_threshold: "20000"
      autovacuum_vacuum_scale_factor: "0.0"
      autovacuum_analyze_scale_factor: "0.0"
      autovacuum_naptime: "10s"
      autovacuum_max_workers: "2"
      autovacuum_vacuum_cost_limit: "800"
      autovacuum_vacuum_cost_delay: "10ms"
      vacuum_cost_limit: "800"
      vacuum_cost_delay: "10ms"
      vacuum_freeze_min_age: "500000"
      vacuum_freeze_table_age: "150000000"
      vacuum_multixact_freeze_min_age: "500000"
      vacuum_multixact_freeze_table_age: "150000000"
      autovacuum_vacuum_insert_threshold: "20000"
      autovacuum_vacuum_insert_scale_factor: "0.0"
      log_autovacuum_min_duration: "0"
      
      # Statistics and monitoring
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: "all"
      auto_explain.log_min_duration: "10s"
      exit_on_error: "off"
      
      # WAL settings
      max_slot_wal_keep_size: "10GB"
      wal_keep_size: "2GB"
      wal_receiver_timeout: "5s"
      wal_sender_timeout: "5s"
      
      # Additional settings
      cron.database_name: app_db
      
      # Audit settings
      pgaudit.log: "all, -misc, -read, -write"
      pgaudit.log_catalog: "off"
      pgaudit.log_parameter: "on"
      pgaudit.log_relation: "on"
    pg_hba:
      - hostssl postgres streaming_replica all cert
      - hostssl replication streaming_replica all cert
      - hostssl app_db streaming_replica all cert
      - local all app_user trust
      - host all app_user localhost trust
      - local all postgres trust
      - host all postgres localhost trust
      - host all all 0.0.0.0/0 md5
      - host all all ::0/0 md5
      
  monitoring:
    enablePodMonitor: true
    
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
