apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  values:
    monitoring:
      podMonitorEnabled: true
    # Local environment specific settings
    replicaCount: 1
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 100m
