---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database-pg
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-ks
    - name: cloudnative-pg-ks
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: OCIRepository
    name: infra-source
  path: ./database/local
  prune: true
  wait: true  