---
# Applications: Database and other application services
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-database-postgresql
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cnpg-operator
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/database/postgresql/local
  prune: true
  wait: true
