---
# Infrastructure Components: Operators and infrastructure services
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-operators
  namespace: flux-system
spec:
  dependsOn:
    - name: platform-components
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: platform-source
  path: ./infrastructure/overlays/local
  prune: true
  wait: true
