---
# Infrastructure Components: CNPG Operators
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cnpg-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: bootstrap
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/cloudnative-pg/local
  prune: true
  wait: true
