---
# Platform Components: CRDs, Helm Repositories, and other foundational resources
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-components
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: platform-source
  path: ./platform/overlays/local
  prune: true
  wait: true
